name: Deploy ADL LRS Application (Python)
'on':
  push:
    branches:
      - python3-xapi-2.0
jobs:
  build-and-test:
    runs-on: python:3.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and test
        run: |
          pip3 install -r requirements.txt
          python3 -m unittest discover ./tests

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build-and-test
    steps:
      - name: Configure SSH
        run: |
          echo "Deployed on dev successfully"
          # mkdir -p ~/.ssh
          # echo "${{ secrets.ADL_WEB_SSH_KEY }}" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan lrrs.ci.adlnet.gov >> ~/.ssh/known_hosts

      # - name: Deploy code on Dev
      #   run: |
      #     ssh ubuntu@lrrs.ci.adlnet.gov "cd /home/ubuntu/lrs-test-frontend && git pull origin ${GITHUB_REF#refs/heads/} && sudo docker-compose up -d --build"

  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   environment: staging
  #   needs:
  #     - build-and-test
  #     - deploy-dev
  #   steps:
  #     - name: Configure SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.ADL_STAGIGN_SSH_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan lrstest.staging.adlnet.gov >> ~/.ssh/known_hosts

  #     - name: Deploy code on Staging
  #       run: |
  #         ssh ubuntu@lrstest.staging.adlnet.gov "cd /home/ubuntu/lrs-test-frontend && git pull origin ${GITHUB_REF#refs/heads/} && sudo docker-compose up -d --build"